apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: busybox
spec:
  scheduleTimeoutSeconds: 10
  minMember: 2
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      name: busybox
      labels:
        app: busybox
        pod-group.scheduling.sigs.k8s.io: busybox
    spec:
      schedulerName: kubeflux
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 1000m
